# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://mos-man.be
title: Mosman
email: your-email@domain.com
author: Your Name
description: > # "Mosman is het kunstzinnige repertoire van microlandschappen ontwikkeld door Joachim Sohie. Met voornamelijk inheemse mossoorten creëert Mosman kunstwerken die onze verbeelding weten te prikkelen."
copyright:
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'
port: 4002

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

gems:
    - jekyll-seo-tag
    - jekyll-sitemap


# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url:
  - title: github
    url:
  - title: linkedin
    url:
